name: audioplayersbg
description: A flutter plugin to play audio in the background
version: 0.5.2
author: Trev Burley <scrivvysolutions@gmail.com>
homepage: https://github.com/thirddimensionstudios/audioplayer

flutter:
  plugin:
    androidPackage: bz.rxla.audioplayer
    pluginClass: AudioplayerPlugin

dependencies:
  uuid: 1.0.0
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.50.0 <2.0.0"
